package com.msframework.backend.config;

public enum Permission {
    DASHBOARD_READ,

    USER_READ,
    USER_CREATE,
    USER_UPDATE,
    USER_DELETE,

    DEPARTMENT_READ,
    DEPARTMENT_CREATE,
    DEPARTMENT_UPDATE,
    DEPARTMENT_DELETE,

    AUDIT_READ,

    APPEARANCE_READ,
    APPEARANCE_UPDATE,

    DATABASE_READ,
    DATABASE_UPDATE,

    DOCUMENTATION_READ,

    AUTH_SETTINGS_READ,
    AUTH_SETTINGS_UPDATE,

    SECURITY_READ,
    SECURITY_UPDATE,

    PAYMENTS_READ,
    PAYMENTS_UPDATE,

    IMPORT_DATA,
    EXPORT_DATA,

    CONNECTIONS_READ,
    CONNECTIONS_UPDATE,

    TIMEZONES_READ,
    TIMEZONES_UPDATE,

    WORKSPACE_READ,
    WORKSPACE_UPDATE,

    API_KEY_READ,
    API_KEY_CREATE,
    API_KEY_DELETE
}