server.port=8080

# PostgreSQL Configuration (Matching your docker-compose)
spring.datasource.url=jdbc:postgresql://localhost:5433/msframework
spring.datasource.username=msframework
spring.datasource.password=msframework
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

# Keep the console logs clean
spring.main.banner-mode=off